# Setup
title: MuleSoft's API Designer
tagline: A web-based graphical environment for designing, documenting, and testing APIs.
baseurl: /api-designer
repository: https://github.com/mulesoft/api-designer

collections:
  branchs:
    output: false
